# Generated by Django 3.1.7 on 2021-02-25 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aluno',
            old_name='data_nascimentoo',
            new_name='data_nascimento',
        ),
    ]
